version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USERPOLLING=true
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes: 
      - ./backend:/app
      - /app/node_modules