services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/frontend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes: 
      - ./backend:/backend